version: '3'
services:
  redis:
    image: redis:latest

  backend:
    depends_on:
      - redis
<<<<<<< HEAD
    build:
      context: ./backend
      dockerfile: Dockerfile
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
=======
    image: nicobah/devops_backend:latest
  frontend:
    depends_on:
      - backend
    image: nicobah/devops_frontend:latest
>>>>>>> development
    ports:
      - 9001:8080
