apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment_backend
  name: service-backend
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 5000
  selector:
    app: deployment-backend
  type: ClusterIP
status:
  loadBalancer: {}
