name: Go
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
#    branches:
#      - development

env:
  docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
  docker_password: ${{ secrets.DOCKER_TOKEN }}
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update  && sudo apt-get install golang-go -y
      - name: Build
        run: cd frontend && go build .
      - name: Test
        run: cd frontend && go test .
  Push_to_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}