name: Go
on: [push]
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
      - name: Install dependencies
        run: sudo apt-get update  && sudo apt-get install golang-go -y
      - name: Build
        run: cd frontend && go build .
      - name: Test
        run: cd frontend && go test .
  Push_to_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: upload code
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: login
        run: chmod +x build-docker.sh && build-docker.sh
      - name: push
        run: chmod +x push-docker.sh && push-docker.sh
